### ISSUE TITLE
Generate features(features.npy) Problem-Flickr30K

### ISSUE THREAD

**Issue by jishan900** [neural-nuts/image-caption-generator#24]
```
jishan@jishan-HP-ProBook-450-G3:~/Downloads/fy$ python convfeatures.py --data_path Dataset/flickr30k-images --inception_path ConvNets/inception_v4.pb
Extracting Features
#Images: 3
2018-04-14 01:05:43.501841: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Traceback (most recent call last):
  File "convfeatures.py", line 122, in <module>
    forward_pass(io, args.data_path)
  File "convfeatures.py", line 80, in forward_pass
    print "Progress:" + str(((n_batch) / float(n_batch) * 100)) + "%\n"
ZeroDivisionError: float division by zero
```

How can solve that problem. I faced this problem when i want to generate features.npy file. Please help me. Thanks in advance.

**Comment by fursane** [comment]
@jishan900 I am not sure, but did you try "n_batch = len(files) // batch_size" instead of "n_batch = len(files) / batch_size" in line 56?

**Comment by dust0x** [comment]
Thanks for pointing this out, this is a bug and one of the many inherent flaws of Python 2.

You're using 3 images in this example, and the batch size is 10. Further because `<int> / <int>` is pure integer division in Python 2, when we calculate `n_batch = len(files) / batch_size` [here](https://github.com/neural-nuts/image-caption-generator/blob/832f637c7d1b39b925b7f7d92b2b6bf2185c7b2e/convfeatures.py#L56) the result is that `n_batch = 0` and so `(n_batch) / float(n_batch)` will quite naturally throw a ZeroDivisionError.

This never came to notice because we never used less than `batch_size` number of images. For now, you can simply comment or as a more permanent fix, import `from __future__ import division` at the very beginning of `convfeatures.py`.

**Comment by dust0x** [comment]
Closing as resolved from my end. The identified bug will from now on be referred to in #27.
